markdown extension: support v2.3.1
make-patch-tutorial was failing to run on markdown v2.3.1 with the error:

    Traceback (most recent call last):
      File "../../generate-patch-tutorial.py", line 216, in <module>
        sys.exit(main(sys.argv))
      File "../../generate-patch-tutorial.py", line 211, in main
        generate_html(output, abspatches, options.decorate, options.initial_dir)
      File "../../generate-patch-tutorial.py", line 186, in generate_html
        output.write(markdown.markdown(comment, ["showpatch"]))
      File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 412, in markdown
        return md.convert(text)
      File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 296, in convert
        newRoot = treeprocessor.run(root)
      File "/usr/lib/python2.7/dist-packages/markdown/treeprocessors.py", line 360, in run
        pre[0].text = pre[0].text.rstrip() + '\n'
    AttributeError: 'NoneType' object has no attribute 'rstrip'

This patch fixes this issue which could be found by running the automated
tests.  I don't know exactly which version of markdown introduced this
change but this commit makes it work with v2.3.1.